### ISSUE TITLE
Regarding tool

### ISSUE THREAD

**Issue by swagkarna** [404-ghost/Devil-s-Call#1]
Hi bro how are you this my advice for you. Your repo Devil-s-Call and so on... Was not originally created by you...You have stolen the script from speedx/TBomb and used in your script by mentioning as if you were the author of script.If you copy some ones script give credits ok good bye

**Comment by 404-ghost** [comment]
> Hi bro how are you this my advice for you. Your repo Devil-s-Call and so on... Was not originally created by you...You have stolen the script from speedx/TBomb and used in your script by mentioning as if you were the author of script.If you copy some ones script give credits ok good bye


OK bro I accept you advice
But I am not a programmer, I am just beginner and I am doing this for my time-pass in this quarantine. 
I didn't steal scripts, I just took the method of sms generation(algorithm), most of the sms bomber like speedX, TBomb, bombitup app are using same method. 
In github most of the people are just copying other scripts, copying is not a wrong thing. 
Infact I don't know about python, when I start to see others scripts I understand learn python. 
The best way to learn any programming language is reading others scripts and checking how it's works 
Anyway thanks for your advice bro ✌️
